### ISSUE TITLE
Install with bower

### ISSUE THREAD

**Issue by hadimansouri** [jmouriz/angular-material-badge#1]
It is very useful. Is it possible to provide installing this package with bower?

**Comment by jmouriz** [comment]
@hadimansouri Of course is possible to provide installing with bower, but I personally prefer yarn. You can use some CDN provider like unpkg to use this component while I publish this in bower. I need to learn this step

**Comment by jmouriz** [comment]
@hadimansouri I closed this issue because the bower people invite us to use yarn while this first is maintained.
