### ISSUE TITLE
Love it but z-index causes a bunch of issues.

### ISSUE THREAD

**Issue by Voziv** [jmouriz/angular-material-badge#2]
Using this on a button that shows a dropdown the `z-index: 9999` causes the badge to appear above everything.

Same happens with dialogs and whatnot.

![image](https://user-images.githubusercontent.com/25726/31191857-8367490e-a90d-11e7-9067-b9d8640da3c7.png)

**Comment by jmouriz** [comment]
@Voziv Thanks! I unhardcode the zIndex from directive and add it to css so you can overwrite this property in your own css (may be must use !important)
