### ISSUE TITLE
Resizing the browser causes the icon to no longer be aligned

### ISSUE THREAD

**Issue by Voziv** [jmouriz/angular-material-badge#3]
![image](https://user-images.githubusercontent.com/25726/31192827-4bf71dde-a910-11e7-9b81-058c46a2c227.png)

**Comment by aaronmoller** [comment]
The watcher that's set up on window resize is watching the location of the element itself instead of watching for the parent element to change.

**Comment by aaronmoller** [comment]
@jmouriz I just opened a PR

**Comment by jmouriz** [comment]
@aaronmoller Because the directive restrict is attribute the element itself is really a parent of badge so I simply added a resize listener to digest the scope. Thanks!
