### ISSUE TITLE
Position after hide - show

### ISSUE THREAD

**Issue by rmpt** [jmouriz/angular-material-badge#5]
Attach mg-badge to an element that is shown by default. Hide it and show it again and the badge stays with the style below.
    position: absolute;
    display: initial;
    left: -10px;
    top: -10px;

Look at the image.

![badge_bug](https://user-images.githubusercontent.com/16465379/33804360-f74d345c-dd9a-11e7-9306-981c521bf5fe.jpg)

**Comment by jmouriz** [comment]
Fix in commit 8d976d0645ded0d418e001beca03256edf3f18a9
